version: '3'

services:
  mqtml:
    image: cetciot/mqtt-broker-proxy
    container_name: mqtt-proxy
    network_mode: host
    restart: always
    ports:
      - "18081:18081"
    environment:
      LOG_LEVEL: "debug"
      SRC_PORT: "1883"
      DST_ADDR: "192.168.0.95:1883"